### ISSUE TITLE
Autogenerated Packages.bz2 and Sources.bz2 yield a checksum mismatch

### ISSUE THREAD

**Issue by nblock** [apt-mirror/apt-mirror#26]
On ftp.at.debian.org only Packages.gz, Packages.xz as well as Sources.gz and Sources.xz are available for download [1,2].

Apt-mirror relies on the availability of Packages.bz2 and Sources.bz2. Since those do not exist on ftp.at.debian.org, apt-mirror seems to autocreate them. They appear on the filesystem with a timestamp matching the last apt-mirror run.

If a client issues an `apt-get  update`, those generated files yield a _Hash Sum mismatch_ error.

If Packages.bz2 or Sources.bz2 is not available on the server side, it should not be generated by apt-mirror. Furthermore, once Packages.bz2 or Sources.bz2 disappear on the server side at one point in time, it should also disappear on the mirror side.

affected version: 0.4.9-1

[1] ftp://ftp.at.debian.org/debian/dists/jessie/main/binary-amd64/
[2] ftp://ftp.at.debian.org/debian/dists/jessie/main/source/

**Comment by bdrung** [comment]
apt-mirror should look into the ```dists/$DIST/Release``` file to check which compressions are used. Then apt-mirror will not try do download the autocreated compression files.

**Comment by iredmail** [comment]
Dear developers, still no plan to fix this issue?

**Comment by jjtriff** [comment]
I was having the same problem, but got fixed when I rerun apt-mirror, I guess it is a thing about having everything updated at the same time.
My problem now is configuring to use the local mirror using file:/// and not http://

**Comment by eraserix** [comment]
I think I just got bitten by something very similar today. In my case however, "Packages" had the wrong checksum. Without having investigated in depth, I presume that apt-mirror has created Packages from Packages.gz or something, because our upstream repo only carries Packages.gz and Packages.bz2 (Ubuntu 14.04). Seen on apt-mirror 0.5.1
Why apt-mirror unpacks the existing files I don't know, or why this should result in a file with invalid checksum. After rerunning apt-mirror twice, the error was gone.

**Comment by chutzimir** [comment]
This was fixed with #156. Can be closed.
