### ISSUE TITLE
Add arch specific armhf

### ISSUE THREAD

**Issue by 0iras0r** [apt-mirror/apt-mirror#46]
When I try to mirror this specific architecture debian repo, it fails because apt-mirror recognise deb-armhf as deb-arm.
Why armhf is not available on arch specific support?

**Comment by kohenkatz** [comment]
If you are still using a version of the script which has a whitelist of architecture names (i.e. any version without commit af134bce45a25b650f9b56470b4b9e9c5d155eb5), you need to switch the order of the listed architectures so that `armhf` is before `arm`. Otherwise, `armhf` will never be matched.

Really, it's probably better to update to a version of the script that doesn't limit which architectures it works on.

**Comment by bdrung** [comment]
As kohenkatz explained, this issue is fixed since apt-mirror 0.5.0.
